Added determinant calculator feature
temurchichua/CalculatorAPI pull request #7
Opened 2021-03-18 16:48 UTC by RegiusPythonidae

დავამატე ჩემი ფუნქცია, ასევე init-ში გადავაკეტე get-stddev რადგან ეს ფუნქცია აღარ არსებობდა და ხელს მიშლიდა ლოკალურად ტესტირებაში.

2021-03-18 18:33 UTC, temurchichua requested changes

2021-03-18 18:33 UTC, temurchichua commented on myapp/routes/determinant_calculator.py
> +    return result
API-ს მიერ უკან დაბრუნებული მნიშვნელობა უნდა იყოს JSON

2021-03-18 19:28 UTC, RegiusPythonidae commented on myapp/routes/determinant_calculator.py
> +    return result
Done

2021-03-19 02:19 UTC, temurchichua approved these changes

2021-03-19 02:20 UTC, merged